### ISSUE TITLE
Out-of-date prompt-toolkit causes `TypeError` crash on start

### ISSUE THREAD

**Issue by HarryCutts** [scopatz/xonsh#753]
Since upgrading to 0.2.7, running `xonsh` (with or without `--no-rc`) gives me a `TypeError`:

```
$ xonsh --version
('xonsh/0.2.7',)
$ xonsh --no-rc
/usr/local/lib/python3.4/dist-packages/xonsh/shell.py:97: RuntimeWarning: prompt-toolkit version < v0.57 and may not work as expected. Please update.
  warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.7', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/main.py", line 214, in main
    shell.cmdloop()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/ptk/shell.py", line 112, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/ptk/shell.py", line 81, in singleline
    display_completions_in_columns=multicolumn)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/ptk/shortcuts.py", line 71, in prompt
    application=create_prompt_application(message, **kwargs),
TypeError: create_prompt_application() got an unexpected keyword argument 'reserve_space_for_menu'
```

`xonsh --shell-type readline` starts successfully, so I'm guessing the crash is caused by the prompt-toolkit version. I can't remember how I installed prompt-toolkit, so I'll stick with readline for a bit.

I'm running Ubuntu 14.04 x86_64, kernel 3.16.0-67-generic. `xonsh` is installed system-wide using `pip3`. Feel free to ask for any more information you need.

**Comment by scopatz** [comment]
Thanks for reporting @HarryCutts. This should not be a fatal error.

**Comment by scopatz** [comment]
Hi @HarryCutts, I have put in #754, which should fix this issue.  Would you mind trying it out?

**Comment by HarryCutts** [comment]
Hi @scopatz,

I just installed xonsh from the `ptkfix` branch in a virtualenv, and got the same error.

**Comment by scopatz** [comment]
Weird are you sure it isn't slightly different? There may be other invalid keys besides just `'reserve_space_for_menu'`....

 What is the output of the `xonfig` command when running in the readline shell?

**Comment by HarryCutts** [comment]
The output is:

```
/home/harry/dev/xonsh/venv/lib/python3.4/site-packages/xonsh/shell.py:97: RuntimeWarning: prompt-toolkit version < v0.57 and may not work as expected. Please update.
  warn(msg, RuntimeWarning)
Could not find xonsh configuration or run control files.
TypeError: create_prompt_application() got an unexpected keyword argument 'reserve_space_for_menu'
Traceback (most recent call last):
  File "venv/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.7', 'console_scripts', 'xonsh')()
  File "/home/harry/dev/xonsh/venv/lib/python3.4/site-packages/xonsh/main.py", line 214, in main
    shell.cmdloop()
  File "/home/harry/dev/xonsh/venv/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 112, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/harry/dev/xonsh/venv/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 81, in singleline
    display_completions_in_columns=multicolumn)
  File "/home/harry/dev/xonsh/venv/lib/python3.4/site-packages/xonsh/ptk/shortcuts.py", line 73, in prompt
    application=create_prompt_application(message, **kwargs),
TypeError: create_prompt_application() got an unexpected keyword argument 'reserve_space_for_menu'
```

**Comment by gforsyth** [comment]
Hey @HarryCutts, can you see if `xonsh` will start up with the `readline` shell by running `xonsh --shell-type readline` and then posting the output of `xonfig`?  Thanks!

**Comment by scopatz** [comment]
Erroneous close by #754 merge

**Comment by HarryCutts** [comment]
Hi @gforsyth,

The output of `xonfig` is:

```
+------------------+-------+
| xonsh            | 0.2.7 |
| Python           | 3.4.3 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | <0.57 |
| pygments         | 2.0.2 |
| on posix         | True  |
| on linux         | True  |
| on arch          | False |
| on windows       | False |
| on mac           | False |
| are root user    | False |
| default encoding | utf-8 |
+------------------+-------+
```

**Comment by gforsyth** [comment]
Hmm, well, there's nothing particularly strange looking there, and it does seem like @scopatz fix should have taken care of the problem.  Would you mind trying a `pip3` install from the current git master and checking if the issue persists?  We're only a few commits past `0.2.7` and everything should work at least as well as it currently is.  

```console
pip3 install git+git://github.com/scopatz/xonsh.git
```

**Comment by HarryCutts** [comment]
OK, the issue still persists after updating to current git master. `xonfig` output is unchanged.

**Comment by gforsyth** [comment]
Ok, support for `prompt_toolkit` < v1.0.0 has been deprecated and now starting with an older version will make `xonsh` change to the `readline` shell after throwing an error.  

Closing this but please reopen if the issue persists.  Thanks!
